# Generated by Django 4.1.3 on 2023-01-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("phone", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("qualification", models.CharField(max_length=225)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Cardiologist", "Cardiologist"),
                            ("Dermatologists", "Dermatologists"),
                            (
                                "Emergency Medicine Specialists",
                                "Emergency Medicine Specialists",
                            ),
                            ("Allergists/Immunologists", "Allergists/Immunologists"),
                            ("Anesthesiologists", "Anesthesiologists"),
                            ("Colon and Rectal Surgeons", "Colon and Rectal Surgeons"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientDischargeDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientName", models.CharField(max_length=40)),
                ("DoctorName", models.CharField(max_length=40)),
                ("address", models.CharField(max_length=40)),
                ("mobile", models.BigIntegerField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=5,
                    ),
                ),
                ("weight", models.IntegerField()),
                ("symptoms", models.CharField(max_length=100, null=True)),
                ("ailment", models.CharField(max_length=255)),
                ("medicine", models.TextField()),
                ("admitDate", models.DateField()),
                ("releaseDate", models.DateField()),
                ("daySpent", models.PositiveIntegerField()),
                ("roomCharge", models.PositiveIntegerField()),
                ("medicineCost", models.PositiveIntegerField()),
                ("doctorFee", models.PositiveIntegerField()),
                ("OtherCharge", models.PositiveIntegerField()),
                ("total", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("phone", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "male"), ("female", "female")], max_length=10
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=5,
                    ),
                ),
                ("weight", models.IntegerField()),
                ("symptoms", models.CharField(max_length=100)),
                ("admitDate", models.DateField(auto_now=True)),
                ("status", models.BooleanField()),
                (
                    "doctorName",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.doctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.IntegerField()),
                ("name", models.CharField(max_length=225)),
                ("phone", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("symptoms", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "doctorName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.doctor",
                    ),
                ),
            ],
        ),
    ]
