# Generated by Django 4.1.3 on 2023-01-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="status",
        ),
    ]
