# Generated by Django 4.1.3 on 2023-01-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_remove_patient_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="app_id",
        ),
    ]
