# Generated by Django 4.1.3 on 2023-01-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_remove_appointment_app_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientdischargedetails",
            old_name="DoctorName",
            new_name="doctorName",
        ),
        migrations.RenameField(
            model_name="patientdischargedetails",
            old_name="patientName",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="patientdischargedetails",
            old_name="mobile",
            new_name="phone",
        ),
        migrations.AddField(
            model_name="patientdischargedetails",
            name="email",
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
    ]
